Projekt2025/Pages/AdminUser/AdminDashboard.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Projekt2025.Interfaces;
using System.Collections.Generic;
using Projekt2025.Models;

namespace Projekt2025.Pages.AdminUser
{
    public class AdminDashboardModel : PageModel
    {
        private readonly fgonline_dk_db_zooContext _context;
        private readonly IAdmin _adminService;
        public AdminDashboardModel(IAdmin adminService, fgonline_dk_db_zooContext context)
        {
            _adminService = adminService;
            _context = context;
        }

        public IEnumerable<Event> Events { get; set; }

        public void OnGet()
        {
            Events = _adminService.GetEvents();
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/AdminUser/AdminUser");
        }
        
        
    }
}

Projekt2025/Pages/AdminUser/AdminUser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Projekt2025.Pages.AdminUser
{
    public class AdminUserModel : PageModel
    {
        
        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        //hardcoded admin login 
        private readonly string AdminUsername = "admin";
        private readonly string AdminPassword = "admin12";

        public IActionResult OnPostLogin()
        {
            if (Username == AdminUsername && Password == AdminPassword)
            {
                return RedirectToPage("/AdminUser/AdminDashboard");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Invalid username or password.");
                return Page();
            }
        }


        public void OnGet()
        {
        }
    }
}

Projekt2025/Pages/AdminUser/CreateEvent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Projekt2025.Models;

namespace Projekt2025.Pages.AdminUser
{
    public class CreateEventModel : PageModel
    {
        private readonly Projekt2025.Models.fgonline_dk_db_zooContext _context;

        public CreateEventModel(Projekt2025.Models.fgonline_dk_db_zooContext context)
        {
            _context = context;
        }
        [BindProperty]
        public Event Event { get; set; } = default!;

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Events.Add(Event);
            await _context.SaveChangesAsync();

            return RedirectToPage("AdminDashboard");
        }
    }
}

Projekt2025/Pages/AdminUser/DeleteEvent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Projekt2025.Models;

namespace Projekt2025.Pages.AdminUser
{
    public class DeleteEventModel : PageModel
    {
        private readonly Projekt2025.Models.fgonline_dk_db_zooContext _context;

        public DeleteEventModel(Projekt2025.Models.fgonline_dk_db_zooContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Event Event { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventEntity = await _context.Events.FirstOrDefaultAsync(m => m.EventId == id);

            if (eventEntity is not null)
            {
                Event = eventEntity;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventEntity = await _context.Events.FindAsync(id);
            if (eventEntity != null)
            {
                Event = eventEntity;
                _context.Events.Remove(Event);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("AdminDashboard");
        }
    }
}

Projekt2025/Pages/AdminUser/EditEvent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projekt2025.Models;

namespace Projekt2025.Pages.AdminUser
{
    public class EditEventModel : PageModel
    {
        private readonly Projekt2025.Models.fgonline_dk_db_zooContext _context;

        public EditEventModel(Projekt2025.Models.fgonline_dk_db_zooContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Event Event { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventEntity = await _context.Events.FirstOrDefaultAsync(m => m.EventId == id);
            if (eventEntity == null)
            {
                return NotFound();
            }
            Event = eventEntity;
            return Page();
        }

        
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Event).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EventExists(Event.EventId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("AdminDashboard");
        }

        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.EventId == id);
        }
    }
}

Projekt2025/Pages/AdminUser/AdminDashboard.cshtml
@page
@model Projekt2025.Pages.AdminUser.AdminDashboardModel
@{
    ViewBag.Title = "Admin Dashboard";
}

<h2>Velkommen til Admin Dashboard</h2>
<p>Du er nu logget ind som Admin</p>

<p>
    <a asp-page="CreateEvent">Opret nyt event</a>
</p>


@if (Model.Events != null && Model.Events.Any())
{
    @foreach (var item in Model.Events)
    {
        <table class="table">
            <thead>
                <tr>
                    <td>@item.EventId</td>
                    <td>@item.Title</td>
                    <td>@item.EventDateTimeStart</td>
                    <td>@item.Description</td>
                    <td>@item.Location</td>
                    <td>@item.Price</td>
                    <td>@item.Participants</td>
                    <td>@item.EventDateTimeEnd</td>
                    <td>
                        <a asp-page="EditEvent" asp-route-id="@item.EventId">Edit</a> |
                        <a asp-page="DeleteEvent" asp-route-id="@item.EventId">Delete</a>
                    </td>
                </tr>
            </thead>
        </table>
    }
}


<form method="post" asp-page-handler="Logout">
    <button type="submit" class="btn btn-primary">Logout</button>
</form>

Projekt2025/Pages/AdminUser/AdminUser.cshtml
@page
@model Projekt2025.Pages.AdminUser.AdminUserModel
@{
    ViewData["Title"] = "Admin Login";
}

<h1>Login to access the dashboard</h1>

<form method="post" asp-page-handler="Login">
    <div class="form-group">
        <label for="Username">Username</label>
        <input type="text" id="Username" name="Username" class="form-control" asp-for="Username" required />
    </div>
    <div class="form-group">
        <label for="Password">Password</label>
        <input type="password" id="Password" name="Password" class="form-control" asp-for="Password" required />
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

@if (!ModelState.IsValid)
{
    <div class="text-danger">
        @Html.ValidationSummary()
    </div>
}

Projekt2025/Pages/AdminUser/CreateEvent.cshtml
@page
@model Projekt2025.Pages.AdminUser.CreateEventModel

@{
    ViewData["Title"] = "CreateEvent";
}

<h1>Opret event</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.Title" class="control-label"></label>
                <input asp-for="Event.Title" class="form-control" />
                <span asp-validation-for="Event.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.Description" class="control-label"></label>
                <input asp-for="Event.Description" class="form-control" />
                <span asp-validation-for="Event.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.EventDateTimeStart" class="control-label"></label>
                <input asp-for="Event.EventDateTimeStart" class="form-control" />
                <span asp-validation-for="Event.EventDateTimeStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.Location" class="control-label"></label>
                <input asp-for="Event.Location" class="form-control" />
                <span asp-validation-for="Event.Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.Price" class="control-label"></label>
                <input asp-for="Event.Price" class="form-control" />
                <span asp-validation-for="Event.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.Participants" class="control-label"></label>
                <input asp-for="Event.Participants" class="form-control" />
                <span asp-validation-for="Event.Participants" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.EventDateTimeEnd" class="control-label"></label>
                <input asp-for="Event.EventDateTimeEnd" class="form-control" />
                <span asp-validation-for="Event.EventDateTimeEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Opret" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="AdminDashboard">Tilbage til dashboard</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Projekt2025/Pages/AdminUser/DeleteEvent.cshtml
@page
@model Projekt2025.Pages.AdminUser.DeleteEventModel

@{
    ViewData["Title"] = "DeleteEvent";
}

<h1>Slet event</h1>

<h3>Er du sikker på, at du vil slette dette event?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.EventDateTimeStart)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.EventDateTimeStart)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Location)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.Participants)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Participants)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.EventDateTimeEnd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.EventDateTimeEnd)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Event.EventId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="AdminDashboard" class="btn btn-primary">Cancel</a>
    </form>
</div>

Projekt2025/Pages/AdminUser/EditEvent.cshtml
@page
@model Projekt2025.Pages.AdminUser.EditEventModel

@{
    ViewData["Title"] = "EditEvent";
}

<h1>Rediger event</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Event.EventId" />
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.Title" class="control-label"></label>
                <input asp-for="Event.Title" class="form-control" />
                <span asp-validation-for="Event.Title" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="Event.EventDateTimeStart" class="control-label"></label>
                <input asp-for="Event.EventDateTimeStart" class="form-control" />
                <span asp-validation-for="Event.EventDateTimeStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.Description" class="control-label"></label>
                <input asp-for="Event.Description" class="form-control" />
                <span asp-validation-for="Event.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">*</span>
                <label asp-for="Event.Location" class="control-label"></label>
                <input asp-for="Event.Location" class="form-control" />
                <span asp-validation-for="Event.Location" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="Event.Price" class="control-label"></label>
                <input asp-for="Event.Price" class="form-control" />
                <span asp-validation-for="Event.Price" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="Event.Participants" class="control-label"></label>
                <input asp-for="Event.Participants" class="form-control" />
                <span asp-validation-for="Event.Participants" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="Event.EventDateTimeEnd" class="control-label"></label>
                <input asp-for="Event.EventDateTimeEnd" class="form-control" />
                <span asp-validation-for="Event.EventDateTimeEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="AdminDashboard">Tilbage til dashboard</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}